### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by frodsan** [frodsan/tynn#1]
UPDATE ME!

(╯°□°）╯︵ ┻━┻

**Comment by moonglum** [comment]
This is not very descriptive :laughing: I guess this is about writing [the tutorial](http://tynn.xyz/tutorial.html), right?

So I was thinking about the tutorial page compared to the [routing basics](http://tynn.xyz/guides/routing-basics.html) page. Where do you see the difference?

I really love the [Syro tutorial](http://files.soveran.com/syro/), do you want to do something similar? Or do you have different plans?

**Comment by moonglum** [comment]
I thought about writing something that combines the [Syro tutorial](http://files.soveran.com/syro/) with the [cURL tutorial](http://curl.haxx.se/docs/manual.html). Would you be interested in a PR for that?

**Comment by frodsan** [comment]
> This is not very descriptive :laughing: 

Yup :-p ... Thank you for reminding me. I can update the description after our conversation.

> I really love the Syro tutorial, do you want to do something similar?

I love the Syro tutorial too. Since, Tynn is Syro+default plugins, I think we should do something similar. Maybe we can cover these topics in the tutorial:

- Explaining the basics of a hello world app.
- Matching path segments
- Capturing path segments
- Matching booleans (Maybe?)
- Handling request/response
- Composing applications
- Using plugins (Rendering templates is a good example)
- Running a webserver (Probably talk about Rack here?)

Then, we can use guides to document more features from Tynn/Syro. For example, "Routing Basics" can have more information about the supported method matches (`put/patch/etc`).

Also, I would like to know what do you think about the "Getting Started" page? A friend recommended me to have a generator so people can start easily. I'm building this: https://github.com/frodsan/tynn-generator. It's like express-generator for express.

> Or do you have different plans?

My initial idea was to generate a hello world app in the "Getting Started" page and then in the "Tutorial" page show how it works and extend it so you can learn more features about the router, plugins, etc. But I'm open to suggestions :-)

Thanks!

**Comment by moonglum** [comment]
I'm hacking on some documentation right now to demonstrate the style I would suggest. Will put it into a PR as soon as possible, so we can discuss something concrete :smile: Thanks for the push rights, my friend :heart: 

I think the topics you listed are all important. I think one important thing about Tynn is the multiple ways you can enhance it (helpers, plugins and middlewares). The tutorial should explain what those three things are and when to use which of the three ways – and then point to more documentation.

I think the generator is nice – but I'm not sure how far to go with it. It makes me think about your Cuba template, and how much it helped me when trying out Cuba. Should it also provide a folder structure? Soveran gives an example folder structure in his tutorial as well.

Now, let me hack on the tutorial. *me puts :headphones: on*

**Comment by frodsan** [comment]
> I think the topics you listed are all important. I think one important thing about Tynn is the multiple ways you can enhance it (helpers, plugins and middlewares). The tutorial should explain what those three things are and when to use which of the three ways – and then point to more documentation.

I couldn't agree more :+1: 

> I think the generator is nice – but I'm not sure how far to go with it.

Ok, so maybe is better to move the generator from the "Getting Started" page to another page into "Guides". And keep "Getting Started" and "Tutorial" simple, like the Syro tutorial :-)

> Should it also provide a folder structure? 

Maybe, we can explain this in a different page under "Guides". Like:

````
...
- Testing
- Application Structure
- Application Generator
```

**Comment by moonglum** [comment]
I made a first draft of a basic tutorial in #14 – what do you think? (should we discuss it here or in the PR? Not sure).

Yep, I think the generator should be part of the guides. Maybe alongside the `Application Structure` chapter? I'm not entirely sure where to draw the line between Getting Started and Tutorial. The page I wrote could very well be the Getting Started page.

**Comment by moonglum** [comment]
I can also imagine doing it like this: Rename the quick start section to `tutorial`, rename the old tutorial page to getting started and remove the old getting started page. Add more chapters to the tutorial section.

**Comment by frodsan** [comment]
> I made a first draft of a basic tutorial in #14 – what do you think? (should we discuss it here or in the PR? Not sure).

Looks very good! :smile: ... I think it's fine if we discuss it here.

> I can also imagine doing it like this: Rename the quick start section to tutorial, rename the old tutorial page to getting started and remove the old getting started page. Add more chapters to the tutorial section.

Maybe:

```
Getting Started
- Hello World!
...
...
```

> remove the old getting started page

Yeah, let's do it :scissors:

**Comment by moonglum** [comment]
Ok, reorganized (see PR)! It now looks like this:

<img width="266" alt="Navigation" src="https://cloud.githubusercontent.com/assets/95788/11484853/a7a0d878-97b0-11e5-9961-01f63dbc00c5.png">

**Comment by moonglum** [comment]
I think the chapters for the tutorial should be (building on what you wrote above):

* Getting started (with the content approximately what it is right now)
* Capturing path segments and the inbox
* Handling request/response
* Composing applications
* Extending Tynn (helpers, plugins and middlewares)

What do you think?

**Comment by frodsan** [comment]
I like it. I think that covers the most important features :-)

**Comment by moonglum** [comment]
Ok, I'll continue working on it :smile:

**Comment by moonglum** [comment]
Done in #14
