### ISSUE TITLE
When nothing matches, raise a 404

### ISSUE THREAD

**Issue by moonglum** [frodsan/tynn#12]
In Cuba, when you have unmet conditions, you will get a 404. In Syro (and therefore Tynn) it will just return an empty response with a 200 status code. I know that you [were involved](https://github.com/soveran/cuba/pull/49) in the process of defining that behavior in Cuba, what do you think should be done for Tynn? As far as I can see, it doesn't offer a `default` block like Cuba did :smile:

**Comment by frodsan** [comment]
Syro kept the same behaviour:

```
require "tynn"
require "tynn/test"

Tynn.define do
  get do
    res.write("hello")
  end
end

app = Tynn::Test.new
app.get("/notexists")

raise unless 404 == app.res.status
raise unless app.res.body.empty?
```

**Comment by frodsan** [comment]
I think it's ok to add a default matcher. Here are the options:

```
def default
  return true
end

# on default do
# end
```

Or:

```
def default
  yield
end

# default do
# end
```

Also, do you think it should be included by default or shipped as a plugin?

**Comment by moonglum** [comment]
Yes,  you are absolutely right. It returns a 404 status code (I must have done something weird oO) :smile: I think that is the correct behavior, and should definitely be the default :+1:

About the default matcher: I think that's useful and should exist. I think in the way that Tynn works, it should definitely by a plugin. I like the way that Tynn has a strong emphasis on plugins – and it is so easy to include a plugin that I think this should be one as well.

**Comment by frodsan** [comment]
:+1: I made this: https://github.com/frodsan/tynn/pull/13 Let me know what u think :-)
