### ISSUE TITLE
Accessing Request Headers

### ISSUE THREAD

**Issue by moonglum** [frodsan/tynn#17]
It seems that neither Rack nor Syro provide an easy/obvious way to access HTTP headers of requests. I consider this a pretty important feature, shall we add it on the Tynn level? I suggest an API like this:

```ruby
req.header('Accept-Charset')
```

From my understanding, the way to access the header `Accept` in Rack is the following:

```ruby
req.env['HTTP_ACCEPT_CHARSET']
```

I would go a very simple route by adding the following method to Tynn::Request:

```ruby
def header(name)
  env["HTTP_#{name.tr('-', '_').upcase}"]
end
```

I'm also ok with including this via a plugin, but I vote for including it by default. Headers are a crucial component of HTTP and therefore should be supported in a straightforward way by an HTTP library in my opinion :smile: If you like that, I'll code it and send a PR :smile:

**Comment by frodsan** [comment]
I like the idea to easy access HTTP headers, but I also think
it adds room for more features like asking if a header exists
or fetch and provide a default if it doesn't, like:

```
req.header?("Accept-Charset") # req.env.key?(env_name(x))
req.fetch_header("Accept-Charset")
```

If that's the case, then I think it's probably better
to wrap that behaviour in a class. Like:

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/headers.rb

Or do you think is too much?

This could be useful as well:

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/headers.rb#L106

PD: Can you think in some scenario where you need to change a header in the request?

**Comment by moonglum** [comment]
Very good point, yes. I think one way to achieve that is to make `header` a Ruby Hash. That's something people are familiar with and it then provided all the methods one could need when handling key/value pairs. This has one downside though: Rack (for some reason that is absolutely beyond me) transforms headers in a really, really weird way. It replaces all `-` with `_` and then upcases everything. Unfortunately that is a function that is not reversible :sob: The canonical way to write a header however is like this: `Accept-Charset`. With the method I described above, users can enter it this way or all lowercase, uppercase or even with the underscores. I think we will loose this capability when we transform it into a Hash.

What do you think?

I can't think of any reason to change the headers in the request except in a middleware.

**Comment by frodsan** [comment]
> Very good point, yes. I think one way to achieve that is to make header a Ruby Hash.

Not sure, Ruby Hash is big

```ruby
{}.methods.count
# => 150
```

I think I prefer Rails' implementation for this behaviour:


```
def headers
  @headers ||= Headers.new(self)
end

class Headers
  def [](key)
    req.env[do_transformation(key)]
  end

  # more helper methods ...
end
```

**Comment by britishtea** [comment]
Rack provides the [`HeaderHash`](https://github.com/rack/rack/blob/1-6-stable/lib/rack/utils.rb#L477) utility class in `Rack::Utils` for this purpose. Since you're pretty much guaranteed to have it available when using Tynn, I think it's worth considering.

**Comment by moonglum** [comment]
Thanks for the pointer, @britishtea – did not know that :smile:

I think I agree with the argument of Hash being pretty big. Also I think the Hash-like object should be immutable. I see the following methods in Rails' Headers class:

* `[]`: Yes
* `[]=`: No, we don't want to change the headers
* `add`: No, we don't want to change the headers
* `key?`: Yes
* `fetch`: Yes
* `merge`: Not sure.
* `merge!`: No, we don't want to change the headers.
* `env`: Um, why?
* `each`: I think it is mainly there for Enumerable. Could be useful.
* The entirety of Enumerable: Phew.

I would suggest going with `[]`, `fetch` and `key?` for the first version and see if people bring up valid use cases for the other ones.

**Comment by moonglum** [comment]
Let's also not forget that certain headers already have query methods in Rack::Request:

* `accept_encoding`
* `accept_language`
* `content_charset`
* `content_length`
* `content_type` (and `media_type`)
* `referer`
* `user_agent`

**Comment by moonglum** [comment]
I also like including it this way, because it is symmetrical to how Syro allows you to get and set response headers (via `req.headers[]` and `req.headers[]=`), which makes me think that it probably should be part of Syro :confused:

**Comment by frodsan** [comment]
> I would suggest going with [], fetch and key? for the first version and see if people bring up valid use cases for the other ones.

:+1: 

> which makes me think that it probably should be part of Syro :confused:

You can ask. I'm ok to add it to Tynn::Request if it doesn't get accepted in Syro.

**Comment by frodsan** [comment]
This issue about HeaderHash performance looks interesting: https://github.com/rack/rack/issues/738

**Comment by moonglum** [comment]
Ok, let's see what the discussion about putting it into Syro yields. 

Performance: I think by only instantiating the header object when it is accessed the first time, the performance impact will be very low. What do you think?

**Comment by frodsan** [comment]
> Performance: I think by only instantiating the header object when it is accessed the first time, the performance impact will be very low. What do you think?

Yes, I think the impact will be very low. Anyway, if that's a problem, you can use env["HTTP_x"].
