### ISSUE TITLE
Plugins vs. Helpers

### ISSUE THREAD

**Issue by moonglum** [frodsan/tynn#20]
From what I've understood, helpers are functionally a subset of plugins. For example we could replace the following helper:

```ruby
module TextHelpers
  def moo(str)
    "moo #{str}"
  end
end
```

with the following plugin:

```ruby
module TextPlugin
  module InstanceMethods
    def moo2(str)
      "moo #{str}"
    end
  end
end
```

Which raises the question: When should I use which one? And: Does Tynn need both, or are plugins enough?

**Comment by moonglum** [comment]
(I understand that `helpers` is simple module inclusion from Ruby, and not really a feature of Tynn. But the documentation etc. is advertising it :wink:)

**Comment by frodsan** [comment]
The idea of plugins vs simple modules is that if a module contains constants, other classes/modules or helper methods, they aren't included in Tynn: https://github.com/frodsan/tynn/commit/e0807feecc298d0f9c6cc87a1794c77a1420e56

I think we should remove the "Helpers" section. What do you think?

**Comment by moonglum** [comment]
Understood :smile:

:+1: to removing everything about helpers from the manual. The helper section however contains info on how to use the methods from your views, this should be moved over to the plugins section.
