### ISSUE TITLE
Plugin for PUT/DELETE Forms

### ISSUE THREAD

**Issue by moonglum** [frodsan/tynn#9]
Currently hacking on my first Tynn app. Really, really like it so far – thank you so much :heart: 

I ran into the good old problem that HTML Forms only support GET and POST. The usual solution to simulate a PUT is the following:

```html
<form method="post" action="{{ bla }}">
  <input type="hidden" name="_method" value="put">
  ...
</form>
```

Now I want to write a Plugin that takes a POST request like that, sets the method to PUT and removes the `_method` from the parameters. And of course I want to send you a PR to get my first commit into Tynn :smile: But currently I don't see how to do that. I've read soveran's [Customizations](http://files.soveran.com/syro/ch10.html) chapter for Syro and your [Plugins](http://tynn.xyz/guides/plugins.html) guide. But it seems like they only allow me to add methods, not manipulate the request object itself – right? Do you have any hints for me on how to continue here? Do I need to write a middleware instead? What would be the Tynn Way :tm: to do that?

**Comment by frodsan** [comment]
Hey! How is it going? You can use [Rack::MethodOverride](https://github.com/rack/rack/blob/master/lib/rack/method_override.rb)

```
Tynn.use(Rack::MethodOverride)
```

I would add a section for this in the documentation.

There are 2 ways to manipulate req/res objects now:
you can override the methods from the Syro API and call super, or create a middleware.

One of my plans, is to include support for the new event based middleware for Rack 2.0: [Rack::Events](https://github.com/rack/rack/commit/c393176b0edf3e5d06cabbb6eb9d9c7a07b2afa7). So far there is only one plugin that uses Rack middleware (the SSL plugin), so I don't have that many use cases to include support now. But I think that's a good way to handle the req/res lifecycle.

Thanks for trying it :heart:

**Comment by moonglum** [comment]
Hey @frodsan :smile: Everything's great. I hope you're fine as well? :smile: 

It works! Thank you so much. If you want help with your documentation and guides, I'm more than happy to help!

The two ways sound more than reasonable :smile: 

So `.use` is for Middlewares, and `.plugin` is for Plugins?

**Comment by moonglum** [comment]
Where can I find the repo for `tynn.xzy`?

**Comment by frodsan** [comment]
> Hey @frodsan :smile: Everything's great. I hope you're fine as well? :smile:

Everything good! :-)

> So .use is for Middlewares, and .plugin is for Plugins?

Yes ... I should include that in the docs as well

> If you want help with your documentation and guides, I'm more than happy to help!

Thanks! Everything is in this repository:

https://github.com/frodsan/tynn/tree/master/docs

There are some tasks to generate the website:

```
make pages    # Generate pages
make rdoc       # Generate API docs
make server    # Run server on localhost, port 4000
```

I listed the dependencies on `.gems.docs`, you can install
it with:

```
$ cat .gems.docs | xargs gem install
```

Any ideas to improve the development of the project are welcome! :-)

**Comment by moonglum** [comment]
Awesome :+1: Works, now hacking on my first contribution.
